### ISSUE TITLE
Standalone Application

### ISSUE THREAD

**Issue by mattdrepo** [ronaldloyko/linkbox#21]
Please consider a standalone application.  I want to continue using this, but organising my Firefox better has been the resolve to date.  The process of keeping links well managed in this - is the appeal, However, the rigmarole of getting the links out and making sense of them elsewhere - is the downfall.  Can you not whip up a temporary electron app, till you are where you want to be with the Android project?

**Comment by ronaldloyko** [comment]
Hi @mattdrepo 
I'm planning a major release where Linkbox will be offered as a universal app for several platforms (PWA, Electron, Android etc.).
Since the current code base is geared towards Android, I don't think an Electron app is possible in a hurry.
But that's definitely on the roadmap.
I will soon have more time to work on the new release.

In the meantime you could clone the repo, run `npm i && npm run develop` and it will open the PWA version in your browser.

**Comment by mattdrepo** [comment]
I'll leave that for now.  And keep an eye on it.  I am steering towards better management of links either via an app like yours or something that could organise and sync with firefox.

**Comment by NeeRaj-2401** [comment]
> In the meantime you could clone the repo, run `npm i && npm run develop` and it will open the PWA version in your browser.


Tried ur pwa it seems amazing, there is just one concern remove that '+' button and make both of them separate 

![image](https://user-images.githubusercontent.com/88180887/193986162-89f31bc8-4ace-4d1b-83d3-9ca02a4a8e04.png) --> ![image](https://user-images.githubusercontent.com/88180887/193986276-677a4fab-0d3a-4bbe-b886-0e516af09091.png)
